[build]
  publish = "public"
  command = "yarn osuny build"

[build.environment]
  HUGO_VERSION = "0.159.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/musique/repetitions/mardi-23-mai/"
  to = "/musique/repetitions/17-janvier-2023/"

[[redirects]]
  from = "/records/"
  to = "/musique/records/"

[[redirects]]
  from = "/11-octobre-2023/"
  to = "/musique/repetitions/11-octobre-2023/"

[[redirects]]
  from = "/23-mai-2023/"
  to = "/musique/repetitions/23-mai-2023/"

